# fly.toml app configuration file generated for fullstackopen-part3-ftb on 2024-05-28T15:31:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstackopen-part3-ftb'
primary_region = 'gru'

[build]

[env]
  MONGODB_URI="mongodb+srv://francobulotas:xTf5vCz6vsm0oVg7@fullstackopen-ftb.hotzxgx.mongodb.net/appPerson?retryWrites=true&w=majority&appName=fullstackopen-ftb"
  PORT = "3000" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
