GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/66564e430f25427972ce7f3d
###
DELETE http://localhost:3001/api/persons/665668564e54bfc20754
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Lucas Rodriguez",
    "number": "1923821938"
}
###
PUT http://localhost:3001/api/persons/6656902405ee21f20546c4c2 HTTP/1.1
content-type: application/json

{
    "name": "pe",
    "number": "1234"
}