GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/66564e430f25427972ce7f3d
###
DELETE http://localhost:3001/api/persons/665668564e54bfc20754
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Lucas Rodriguez",
    "number": "1923821938"
}
###
PUT http://localhost:3001/api/persons/665740d7e9e53bff6f7346cb HTTP/1.1
content-type: application/json

{
    "name": "perez",
    "number": "1234"
}